Update progress indicators
microbit-foundation/ml-trainer pull request #131
Opened 2024-01-10 15:27 UTC by microbit-grace

- Make loading spinners/bars green
- Update training in progress spinner to loading bar
- Add isLoading state for StandardButton that uses same spinner component

https://microbit-global.monday.com/boards/1356069004/pulses/1356427969

2024-01-10 15:27 UTC, microbit-grace commented
Preview: https://progress-indicators.ml-trainer.pages.dev/

2024-01-11 09:51 UTC, microbit-grace commented
Things to fix: 
- [ ] Reset training loading bar after training is complete
- [ ] Update credit link to Github link instead of link to examples
- [ ] Remove use of wait (if the reason for it is not obvious)

2024-01-11 10:54 UTC, microbit-robert commented on src/script/ml.ts
> +export async function trainModel() {
We may as well keep the type and change it to how it use to be.
```suggestion
export async function trainModel(): Promise<void> {
```

Also need to change line 74 from `return false;` to `return;`

2024-01-11 10:55 UTC, microbit-robert commented on src/script/ml.ts
> +        // epoch only increases up to totalNumEpochs - 1
Can we change this comment to something like 'epochs indexed at 0', otherwise it looks like a bug.

2024-01-11 11:03 UTC, microbit-robert requested changes
Mostly looks good. I've added a couple of minor comments.

I don't think we should change StandardButton to take an isLoading prop. I think it's weird for a button to have a loading animation in it. We'll drop this shortly because these buttons will change to "connect" instead of loading.

2024-01-11 11:22 UTC, microbit-robert approved these changes
LGTM. Thanks.

2024-01-11 11:54 UTC, merged